const milkProducts = [
  "Cilonmum Colos Baby 24h",
  "Cilonmum Colos Pedia 24h",
  "Cilonmum For Mum Colostrum 24h",
  "Cilonmum Gludiabet Colostrum 24h",
  "Cilonmum Kid Goat Colostrum 24h",
  "Cilonmum Pedia Goat Colostrum 24h",
  "Cilonmum Diasure Colostrum 24h",
  "Talacmum For Mum",
  "Talacmum Gain",
  "Talacmum Gludiabet",
  "Talacmum Goat Kids",
  "Talacmum Goat Pedia",
  "Talacmum IQ Grow",
  "Talacmum Kalosure Gold",
  "Talacmum Kid Baby",
  "Talacmum Pedia Cool",
  "Colos 24h Premium Kid Baby",
  "Colos 24h Premium",
  "NewSure Colos 24h Kid Plus",
  "Baby Care Colostrum Kid",
  "Bold Milk For Mum Colostrum",
  "Bold Milk Glu Sure Colostrum",
  "Sure IQ Sure Gold",
  "Nance Colostrum 24h Kid",
  "Nance Goat Pedia"
];
